apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        tier: backend
    spec:
      containers:
        - name: azure-vote-back
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: {{ .Values.backend.env.ALLOW_EMPTY_PASSWORD | quote }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}